inventorymanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('master.urls', namespace='master')),
    path("user/", include('user.urls', namespace='user')),
    path("accounts/",include('django.contrib.auth.urls')),
    path("product/", include("product.urls", namespace="product")),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

master/urls.py
from django.urls import path
from master import views


app_name = "master"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("about/", views.about_view, name="about"),
    path("contact/", views.contact_view, name="contact"),
    path("feedback/", views.FeedbackView.as_view(), name="feedback"),
    path("login/", views.login_view, name="login"),
    
]

user/urls.py
from django.urls import path
from user import views



app_name = "user"

urlpatterns = [
    path("register/",views.UserRegisterView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
]

templates/includes/footer.html
<footer class="bg-light text-center p-3">
    All Rights Are Reserved &copy; 2022
    </footer>

templates/includes/messages.html
{% if messages %}
<div class="alert-placeholder">
  {% for message in messages %}
  <div
    class="alert alert-{{ message.tags }} alert-dismissible fade show"
    role="alert"
  >
    {{message}}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>

  {% endfor %}
</div>

<style>
  .alert-placeholder {
    position: fixed;
    top: 100px;
    right: 24px;
    z-index: 10;
  }
</style>
{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">PCMAN</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'master:home' %}">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'master:about' %}">ABOUT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'master:feedback' %}">CONTACT US</a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              Product
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="">List</a></li>
              <li><a class="dropdown-item" href="">Create</a></li>
              <li><hr class="dropdown-divider" /></li>
              <!-- <li><a class="dropdown-item" href="#">Update</a></li> -->
            </ul> 
          </li>
         
          
          

          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="#profile">{{user}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'logout' %}">Logout</a>

        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'login' %}">Login</a>
        
        </li>

        <li class="nav-item">
          <a class="nav-link active" href="{% url 'user:register' %}">Register</a>
        
        </li>
        {% endif %}


  
         
         

         
  
  
  
  
  
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input
            class="form-control me-2"
            type="search"
            placeholder="Search"
            aria-label="Search"
          />
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  