inventorymanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('master.urls', namespace='master')),
    path("user/", include('user.urls', namespace='user')),
    path("accounts/",include('django.contrib.auth.urls')),
    path("product/", include("product.urls", namespace="product")),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from product import views

app_name = "product"

urlpatterns = [
    # product paths
    path("create/", views.ProductCreateView.as_view(), name="create"),
    path("list/", views.ProductListView.as_view(), name="list"),
    path("<int:pk>/detail/", views.ProductDetailview.as_view(), name="detail"),
    path("<int:pk>/delete/", views.ProductDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.ProductUpdateView.as_view(), name="update"),
    path("cart/add/", views.AddToCart.as_view(), name="add_to_cart"),

    # cart
    # path("cart/create/", views.EnrollCreateView.as_view(), name="cart_create"),

]

user/urls.py
from django.urls import path
from user import views



app_name = "user"

urlpatterns = [
    path("register/",views.UserRegisterView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
]

product/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import F, Count, Sum
from master.models import TimeStamp
from customer.models import Customer


USER = get_user_model()


class Category(TimeStamp, models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.name}"


class Unit(models.Model):
    name = models.CharField(max_length=50)
    symbol = models.CharField(max_length=50)
    secondary_unit = models.ForeignKey(
        "self", on_delete=models.SET_NULL, null=True, blank=True
    )
    conversion_rate = models.FloatField(max_length=50)

    def __str__(self) -> str:
        return f"{self.name}"


class Product(TimeStamp, models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField(max_length=250)
    image = models.ImageField(upload_to="product/image", default="default/product.png")
    private = models.BooleanField(default=False)
    stock = models.CharField(max_length=50)
    available = models.BooleanField(default=True)
    user = models.ForeignKey(
        USER, on_delete=models.SET_NULL, null=True, blank=True, default="1"
    )
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.name}"


class Cart(TimeStamp, models.Model):
    user = models.ForeignKey(USER, on_delete=models.SET_NULL, null=True, blank=True)

    def total(self):
        cart_total = CartItem.objects.filter(cart=self, status=True).annotate(
            amount=F("product__price") * F("quantity")
        ).aggregate("amount").get("amount_sum")
        return cart_total

    def __str__(self):
        return f"user: {self.user}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

product/forms.py
from django import forms
from product.models import Product

# create/update form product
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price","description", "unit", "category","image"]

class AddToCartForm(forms.Form):
    product = forms.IntegerField()
    quantity = forms.IntegerField()

product/views.py
from decimal import Decimal

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as views

from product.forms import ProductForm
from product.models import Cart, CartItem, Product

USER = get_user_model()


# create course
class ProductCreateView(views.CreateView):
    template_name = "product/form.html"
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("product:list")
    extra_context = {"action": "Create"}

    # def form_valid(self,form):
    #     form.instance.user=self.request.user
    #     return super().form_valid(form)

    def get(self, request):
        context = {"form": self.form_class()}
        context.update(self.extra_context)
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)

    def form_invalid(self, form):
        context = {"form": form}
        context.update(self.extra_context)
        return render(self.request, self.template_name, context)


# list course
class ProductListView(views.ListView):
    template_name = "product/list.html"
    model = Product
    context_object_name = "products"

    def get_queryset(self):
        qs = Product.objects.filter(status=True)
        return qs


# detail course
class ProductDetailview(views.DetailView):
    template_name = "product/detail.html"
    model = Product
    context_object_name = "product"

    def get_queryset(self):
        qs = Product.objects.filter(status=True)
        return qs


# update course
class ProductUpdateView(views.UpdateView):
    template_name = "product/form.html"
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("product:list")
    extra_context = {"action": "Update"}


# delete course
class ProductDeleteView(views.DeleteView):
    template_name = "product/form.html"
    model = Product
    success_url = reverse_lazy("product:list")
    extra_context = {"action": "Delete", "info": "Are you sure want to delete?"}

    def form_valid(self, form):
        self.object.status = False
        self.object.save()
        url = super().get_success_url()
        return redirect(url)


# class Cart(object):
#     def __init__(self, request):
#         self.session = request.session
#         cart = self.session.get(settings.CART_SESSION_ID)
#         if not cart:
#             cart = self.session[settings.CART_SESSION_ID] = {}
#         self.cart = cart

#     def add(self, product, quantity=1, update_quantity=False):
#         product_id = str(product.id)
#         if product_id not in self.cart:
#             self.cart[product_id] = {'quantity': 0, 'price': str(product.price)}
#         if update_quantity:
#             self.cart[product_id]['quantity'] = quantity
#         else:
#             self.cart[product_id]['quantity'] += quantity
#         self.save()

#     def save(self):
#         self.session[settings.CART_SESSION_ID] = self.cart
#         self.session.modified = True

#     def remove(self, product):
#         product_id = str(product.id)
#         if product_id in self.cart:
#             del self.cart[product_id]
#             self.save()

#     def __iter__(self):
#         product_ids = self.cart.keys()
#         products = Product.objects.filter(id__in=product_ids)
#         for product in products:
#             self.cart[str(product.id)]['product'] = product

#         for item in self.cart.values():
#             item['price'] = Decimal(item['price'])
#             item['total_price'] = item['price'] * item['quantity']
#             yield item

#     def __len__(self):
#         return sum(item['quantity'] for item in self.cart.values())

#     def get_total_price(self):
#         return sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())

#     def clear(self):
#         del self.session[settings.CART_SESSION_ID]
#         self.session.modified = True


class AddToCart(LoginRequiredMixin, views.View):
    def post(self, request):
        product_id = request.POST.get("product_id")
        quantity = request.POST.get("quantity")
        user = request.user

        product = Product.objects.filter(id=product_id).first()
        cart, created = Cart.objects.get_or_create(user=user, status=True)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)

        if created:
            cart_item.quantity = quantity
        else:
            cart_item.quantity += quantity
            
        messages.success(request, "Added successfully!")
        return redirect(reverse_lazy("product:list"))

templates/product/detail.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="col">
      <div class="card shadow-sm mb-3">
        <img src="{{product.image.url}}" alt="..." class="card-img-top" />
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.price}}</p>
          <p class="card-text">{{course.description}}</p>
          <p class="card-text">{{product.private}}</p>
          <p class="card-text">{{product.unit}}</p>
          <p class="card-text">Created by: {{product.user}}</p>
          <p class="card-text text-muted fst-italic">
            Last Updated on: {{product.updated_on|date}}
          </p>

          <div class="text-left">
            
           
            <li class="list-group-item">
              <form action="{% url 'product:add_to_cart' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{product.id}}">
                <input type="number" class="form-control" min="1" name="quantity" value="1">
                <button type="submit" class="btn btn-primary">Add To Cart</button>
              </form>
              
            </li>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/product/form.html
{% extends "base.html" %} {% block content %}

<div class="container" style="max-width: 600px">
  <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Product | <span class="text-primary h4">{{action}}</span></h1>
  </div>
  <div class="py-5">
    <div class="row">
      <div class="col-12">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} 
          {% if info %}
          <p class="text-primary">{{info}}</p>
          {% endif %} {{ form.as_p }}
          <button class="btn btn-primary">{{action}}</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/product/list.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
<div class="container">
  <div
    class="row row-cols-lg-3 g-2 g-lg-3 justify-content-center align-items-center py-5"
  >
    {% for product in products %}
    <div class="col">
      <div class="card shadow-sm mb-3">
        <img src="{{product.image.url}}" alt="..." class="card-img-top" />
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.price}}</p>
          <p class="card-text">{{product.description}}</p>
          <p class="card-text">{{product.category}}</p>
          <p class="card-text">{{product.available}}</p>
          <p class="card-text">{{product.unit}}</p>
          <div class="link-group">
            <ul class="list-group list-group-flush list-group-horizontal">
              <!-- {% if user.is_superuser %} -->

              <li class="list-group-item">
                <a
                  href="{% url 'product:update' product.id %}"
                  class="btn btn-info"
                  >Update</a
                >
              </li>
              <li class="list-group-item">
                <a
                  href="{% url 'product:delete' product.id %}"
                  class="btn btn-danger"
                  >Delete</a
                >
              </li>
              <li class="list-group-item">
                <a
                  href="{% url 'product:detail' product.id %}"
                  class="btn btn-info"
                  >Detail</a
                >
              </li>
              <!-- <li class="list-group-item">
                <form action="{% url 'product:add_to_cart' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="product_id" value="{{product.id}}">
                  <input type="number" class="form-control" min="1" name="quantity" value="1">
                  <button type="submit" class="btn btn-primary">Add To Cart</button>
                </form>
                
              </li>
              {%  else %}
              <li class="list-group-item">
                <form action="{% url 'product:add_to_cart' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="product_id" value="{{product.id}}">
                  <input type="number" class="form-control" min="1" name="quantity" value="1">
                  <button type="submit" class="btn btn-primary">Add To Cart</button>
                </form>
                
              </li> -->
            

              <!-- {% endif %} -->
              

              
            </ul>
          </div>
        </div>
      </div>
    </div>
    {% empty %}
    <div class="col">
      <div class="card shadow-sm mb-3">
        <img src="{{product.image.url}}" alt="..." class="card-img-top" />
        <div class="card-body">
          <h5 class="card-title">Nothing to show!</h5>
          <p class="card-text">{{product.description}}</p>
          <p class="card-text">{{product.duration}}</p>
          <div>
            <a href="#" class="btn btn-primary">Add To Cart</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/product/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="main">
        <!-- Create a Form -->
        <form method="POST">
            <!-- Security token by Django -->
            {% csrf_token %}
     
            <!-- form as paragraph -->
            {{ form.as_p }}
     
            <input type="submit" value="Update">
        </form>
     
    </div>
</body>
</html>